name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Build Docker img
      run: docker build . -t docker-playwright
    - name: Run Docker tests
      run: docker run -v $(pwd)/allure-results:/playwright/allure-results docker-playwright
    - name: Allure report
      run: npx allure-commandline generate --clean -o allure-report allure-results
      continue-on-error: true
    - name: Publish report to Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
    - name: Extract Allure Report Link
      id: extract-link
      run: |
        allureReportLink="https://${{ github.actor }}.github.io/${{ github.repository }}/allure-report"
    - name: ALLURE REPORT
      if: success()
      run: |
        echo "Allure Report: ${{ steps.extract-link.outputs.allure_report_link }}"
    
      
    # - name: Publish report
    #   uses: actions/upload-artifact@v2
    #   with: 
    #     name: allure-report
    #     path: allure-report