name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Build Docker img
      run: docker build . -t docker-playwright
    - name: Run Docker tests
      run: docker run docker-playwright
    - name: Publish Allure reports
      run: docker run docker-playwright
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: allure-report
        path: allure-results/
        retention-days: 3
